name: Cron Job

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install .
      - run: pyimapsync --server_from ${SERVERFROM} --server_to ${SERVERTO} --inboxes ${FOLDERS}
        env:
          FOLDERS: ${{ secrets.FOLDERS_1 }}
          SERVERFROM: ${{ secrets.SERVER_FROM_1 }}
          SERVERTO: ${{ secrets.SERVER_TO_1 }}
      - run: pyimapsync --server_from ${SERVERFROM} --server_to ${SERVERTO} --inboxes ${FOLDERS}
        env:
          FOLDERS: ${{ secrets.FOLDERS_2 }}
          SERVERFROM: ${{ secrets.SERVER_FROM_2 }}
          SERVERTO: ${{ secrets.SERVER_TO_1 }}